baseURL = 'https://www.plakar.io/'
languageCode = 'en-us'
theme = "plakarium"
title = "Plakar - Effortless backup"

[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false


[permalinks]
posts = "/posts/:year-:month-:day/:slug"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"

[Params.github]
enabled = true
organization = "PlakarKorp"
repository = "plakar"

[Params.discord]
enabled = true
inviteCode = "uuegtnF2Q5"

[Params.bluesky]
enabled = true
account = "plakar.bsky.social"

[Params.X]
enabled = true
account = "PlakarKorp"

[Params.linkedin]
enabled = true
companyID = "plakarkorp"

[Params.axeptio]
enabled = true
clientId = "670b04f487d8b40de2e7f22c"
cookiesVersion = "plakar-fr-EU-2"

[Params.googleAnalytics]
enabled = true
id = "G-4EJ3HLL4HS"


