disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Effortless distributed backup"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/Plakar_Effortless_Backup.png"
